from .templates import (
    EXPLAINABLE_ANALYSIS_PROMPT,
    AI_TRANSITION_WORDS,
    GENERIC_FILLER_PHRASES,
    AI_CLICHE_VOCABULARY,
)

__all__ = [
    "EXPLAINABLE_ANALYSIS_PROMPT",
    "AI_TRANSITION_WORDS",
    "GENERIC_FILLER_PHRASES",
    "AI_CLICHE_VOCABULARY",
]
